server:
  port: 8081
  
    
logging:
  level:
    org.springframework: info
    org.springframework.security: debug
    org.springframework.web: debug
    web: debug

spring:
  security:
    user:
      name: dominik
      password: pass    
    oauth2:
      client:
        registration:
          google:
            client-id: 148971885543-co9dv22tjamh7amdonnqod69dsd721rp.apps.googleusercontent.com
            client-secret: mXAtT6Ze7M7mK_KCb5VEyJSY    
bookdemo:
    stringprop: a value with spaces
    numProp: 42  
    nested:
        configParam: 23

    
    
---
spring:
  profiles: ci
  
server:
  port: 8081
  
bookdemo:
    stringprop: a NEW value with spaces
    #numProp: 42